### PR TITLE
Fix can send websocket message after close

### LINKED ISSUE #7: WebSocket client get stale connection when server closes the connection
On branch [add_websocket](https://github.com/IBM/fluent-forward-go/tree/add_websockets)

When the WebSocket server drops an established connection the WebSocket client still can invoke `SendMessage()` without getting an error.

### PR DESCRIPTION
**Pull request by ericmillin**
Fixes #7 where you could send on a closed websocket connection.

 Also added an app for manual testing.

### CODE REVIEW

File: cmd/ws/listener.go [hunk 1]
```diff
@@ -0,0 +1,111 @@
+package main
+
+import (
```
Comment (ericmillin) [inline cmd/ws/listener.go:3]: This is just to support manual testing

File: fluent/client/ws_client.go [hunk 2]
```diff
@@ -142,25 +179,21 @@ func (c *WSClient) Reconnect() (err error) {
...
+	c.setErr(err)
+
 	return
 }
 
 // SendMessage sends a single msgp.Encodable across the wire.
 func (c *WSClient) SendMessage(e msgp.Encodable) error {
-	if c.Session == nil {
-		return errors.New("No active session")
+	if err := c.getErr(); err != nil {
```
Comment (ericmillin) [inline fluent/client/ws_client.go:189]: These next lines are the meat of the fix. If the connection has errored out, then it will get returned here. If the connection was otherwise closed, it will error below.

File: fluent/client/ws_client.go [hunk 3]
```diff
@@ -142,25 +179,21 @@ func (c *WSClient) Reconnect() (err error) {
...
 	}
 
-	// msgp.Encode makes use of object pool to decrease allocations
-	return msgp.Encode(c.Session.Connection, e)
-}
-
-// Listen starts a read loop on the Session's websocket connection. It blocks until the Session
-// is closed.
-func (c *WSClient) Listen() error {
-	if c.Session == nil || c.Session.Connection == nil {
```
Comment (ericmillin) [inline fluent/client/ws_client.go:161]: Listen is now handled internally in `Connect`.

File: fluent/client/ws_client.go [hunk 4]
```diff
@@ -117,10 +145,19 @@ func (c *WSClient) Connect() error {
...
-		ServerAddress: c.ServerAddress,
-		Connection:    connection,
-	}
+	c.Session = c.ConnectionFactory.NewSession(connection)
+	waitChan := make(chan struct{}, 1)
+
+	go func() {
+		waitChan <- struct{}{}
+
+		if err := c.Session.Connection.Listen(); err != nil {
```
Comment (ericmillin) [inline fluent/client/ws_client.go:154]: The client may not be explicitly handling reads, so they may not know that the connection has been terminated. Store any connection errors here so they can be bubbled to the user next time they call `SendMessage`

File: cmd/ws/main.go [hunk 5]
```diff
@@ -0,0 +1,107 @@
+package main
```
Comment (ericmillin) [inline cmd/ws/main.go:1]: manual test app

File: fluent/client/ws/connection.go [hunk 6]
```diff
@@ -70,10 +69,18 @@ func NewConnection(conn ext.Conn, opts ConnectionOptions) (Connection, error) {
 		})
 	}
 
-	if opts.ReadHandler != nil {
-		wsc.SetReadHandler(opts.ReadHandler)
+	if opts.ReadHandler == nil {
+		opts.ReadHandler = func(c Connection, _ int, _ []byte, err error) error {
+			if err != nil {
+				_ = c.Close()
```
Comment (ericmillin) [inline fluent/client/ws/connection.go:75]: ensures the connection is closed on error, even if the user is not explicitly handling reads

File: fluent/client/ws/connection.go [hunk 7]
```diff
@@ -111,16 +118,21 @@ func (wsc *connection) CloseWithMsg(closeCode int, msg string) error {
 	return nil
 }
 
-func (wsc *connection) enqueueErr(err error) {
-	wsc.closedLock.Lock()
-	defer wsc.closedLock.Unlock()
+func (wsc *connection) Close() error {
+	return wsc.CloseWithMsg(websocket.CloseNormalClosure, "so long and thanks for all the fish")
```
Comment (gufranmirza) [inline fluent/client/ws/connection.go:122]:
```
func (wsc *connection) CloseWithMsg(closeCode int, msg string) error {
	wsc.closedLock.Lock()
	defer wsc.closedLock.Unlock()

	if wsc.connClosed {
		return nil
	}

	wsc.connClosed = true

	err := wsc.WriteMessage(
		websocket.CloseMessage,
		websocket.FormatCloseMessage(
			closeCode, msg,
		),
	)

	if err != nil {
		log.Println("write close failed", err)
		return wsc.Conn.Close()
	}

	return nil
}
```

What happens when `wsc.WriteMessage` does not throw any error, what happens in this case?

File: fluent/client/ws_client.go [hunk 8]
```diff
@@ -117,10 +145,19 @@ func (c *WSClient) Connect() error {
 		return err
 	}
 
-	c.Session = &WSSession{
-		ServerAddress: c.ServerAddress,
-		Connection:    connection,
-	}
+	c.Session = c.ConnectionFactory.NewSession(connection)
+	waitChan := make(chan struct{}, 1)
```
[the remark this answers is not in the document]
Comment (gufranmirza) [reply fluent/client/ws_client.go:149]: Above function will not return the error if `c.Session.Connection.Listen()` returns an error. can be re written as below

```
func (c *WSClient) Connect() error {
	waitChan := make(chan struct{}, 1)
	defer func() {
		close(waitChan)
	}()
	var listenErr error

	if c.Session != nil {
		return errors.New("A session is already active")
	}

	if c.ConnectionFactory == nil {
		c.ConnectionFactory = &DefaultWSConnectionFactory{
			ServerAddress: c.ServerAddress,
			AuthInfo:      c.AuthInfo,
		}
	}

	conn, err := c.ConnectionFactory.New()
	if err != nil {
		return err
	}

	connection, err := ws.NewConnection(conn, c.ConnectionOptions)
	if err != nil {
		return err
	}

	c.Session = c.ConnectionFactory.NewSession(connection)

	go func() {
		if err := c.Session.Connection.Listen(); err != nil {
			listenErr = err
			waitChan <- struct{}{}
		} else {
			waitChan <- struct{}{}
		}
	}()

	// wait for go routine to start
	<-waitChan

	return listenErr
}
```

File: fluent/client/ws_client.go (hunk 2 above)
Comment (gufranmirza) [reply fluent/client/ws_client.go:189]: shouldn't be a connection error returned while we call `c.Session.Connection.Listen()`

**Review by gufranmirza — COMMENTED** [review]
Added few comments

File: fluent/client/ws_client.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (ericmillin) [reply fluent/client/ws_client.go:149]: > The channel `waitChan` will not be closed, so (formally) this will become a memory leak. Why is it buffered? I assume to not block the concurrent function during startup?!
> 
> This can also be achieved without memory leak:
> 
> ```
> waitChan := make(chan struct{})
> go func() {
>    close(waitChan)
>    .
>    .
> }
> 
> <- waitChan
> ```

You don't need to explicitly close channels unless the it's important to the control flow. E.g., the receiver may need to know the channel has been closed so it can exit a loop. In either case, the garbage collector will close the channel when it's no longer needed.

[the remark this answers is not in the document]
Comment (ericmillin) [reply fluent/client/ws_client.go:149]: I'm also adding comments to explain

File: fluent/client/ws/connection.go [hunk 9]
```diff
@@ -111,16 +118,21 @@ func (wsc *connection) CloseWithMsg(closeCode int, msg string) error {
 	return nil
 }
 
-func (wsc *connection) enqueueErr(err error) {
-	wsc.closedLock.Lock()
-	defer wsc.closedLock.Unlock()
+func (wsc *connection) Close() error {
```
[the remark this answers is not in the document]
Comment (ericmillin) [reply fluent/client/ws/connection.go:121]: @BernhardSchmid Yeah... I think I introduced a bug here because `Close` should wait for the read loop to close or timeout. You can see the pattern in this example.

https://github.com/gorilla/websocket/blob/master/examples/echo/client.go#L40-L81

I'll fix it

[the remark this answers is not in the document]
Comment (ericmillin) [reply fluent/client/ws/connection.go:121]: I remember thinking "Why did I make it so complicated before?". Now I know ;)

File: fluent/client/ws_client.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (gufranmirza) [reply fluent/client/ws_client.go:149]: So, as you mentioned `error from Listen does matter to Connect ` then it's ok to start listen asynchronously and we can remove `waitChan `

File: fluent/client/ws_client.go (hunk 2 above)
Comment (gufranmirza) [reply fluent/client/ws_client.go:189]: @ericmillin 

Just a small observation:

We can skip calling `c.Session.Connection.Listen()` if read handler is not set `opts.ReadHandler == nil` it just specifies we are not interested in reading messages from the server. So listening to the server is just overhead.

Comment (ericmillin) [reply fluent/client/ws_client.go:191]: @gufranmirza Without Listen, it won't receive Close messages

Comment (gufranmirza) [reply fluent/client/ws_client.go:191]: Got it, thanks

**Comment by gufranmirza** [comment]
LGTM
